---
title: "change_over_time"
author: "Adelson Aguasvivas"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(sf)
library(rgdal)
library(tidycensus)
library(scales)
library(gt)
library(gridExtra)
library(lemon)
library(rvest)
library(magrittr)
library(leaflet)
library(gganimate)
library(spdplyr)
library(rmapshaper)



```

  
```{r bronx-change-over-time, include=FALSE}

# For the milestone I wanted to create another graph where I compare the change
# in the racial demographics of the five boroughs using webscrapped data from
# wikipedia, so that we can compare the different racial distributions and how
# this plays a part in median income. I started by adding options to have the
# numbers not be in scientific notation. To scrape the data from wikipedia, I
# saved the url, read it in, read the html, found the xpath, made a table then
# cleaned the names using the janitor package. Then, I began to organize my data
# to plot it, first, by selecting the relevant variables, pivoting to organize
# the data better, transforming the population column to numeric, making all the
# NAs to zeros, so that we do not lose this data, even though the census didn't
# keep track of some specific populations like Hispanic/Latinxs at one point.
# Then, I used ggplot, to set the x axis to the year and the y axis to the
# population, using geom_point to create a scatterplot, so we can visualize
# change over time, setting the dots to be the race, and using position_jitter,
# to avoid overplotting, as well as adding alpha, so that we can see through the
# points better, so that we do not miss any of them. I used labs, to give the
# graph a meaningful title, subtitle, and axis names. I used
# scale_color_discrete, to fix the legend and make it display better
# information. Finally, I used scale_x_continuous and scale_y_continuous to set
# the breaks and labels for the axis.

options(scipen=5)

website = 'https://en.wikipedia.org/wiki/Demographic_history_of_New_York_City#The_Bronx'

table_bronx <- website %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>%
  html_table(fill = TRUE) %>%
  clean_names()
  
change_over_time_bronx <- table_bronx %>%
  select(year, white_includes_white_hispanics, 
         black, asian, hispanic_latino, foreignborn) %>%
  pivot_longer(-year, names_to = "race", values_to = "population") %>%
  transform(population = as.numeric(gsub(",", "", population))) %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>%
  ggplot(aes(x = year, y = population, color = race)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.3, 
                                        height = 0), 
             alpha = 0.5) +
  labs(title = "Change in Demographics Over Time in the Bronx, New York",
       subtitle = "Data Webscrapped From Wikipedia. From 1910-2010.",
       x = "Year",
       y = "Population") +
  theme_classic() +
  scale_color_discrete(name = "Race/Census Categories",
                            labels = c("Asian", "Black", "Foreign Born", 
                                       "Hispanic or Latino", "White")) +
  scale_x_continuous(breaks = c(1910, 1920, 1930, 1940, 1950, 
                                1960, 1970, 1980, 1990, 2000, 2010)) +
  scale_y_continuous(breaks = c(0, 250000, 500000, 750000, 1000000, 1250000),
                     labels = c("0", "250,000", "500,000", "750,000",
                                "1,000,000", "1,250,000"))

change_over_time_bronx

bronx_animated_change <- change_over_time_bronx +
  transition_reveal(year) +
  labs(title = "Change in Demographics Over Time in the Bronx. Year: {as.integer(frame_along)}")

# anim_save("bronx_change_animation.gif", path = "shiny/change_over_time_graphs/", 
#          animation = bronx_animated_change)

```

```{r manhattan-change-over-time}

options(scipen=5)

manhattan_website = 'https://en.wikipedia.org/wiki/Demographic_history_of_New_York_City#Manhattan'

table_manhattan <- website %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[4]') %>%
  html_table(fill = TRUE) %>%
  clean_names()
  
change_over_time_manhattan <- table_manhattan %>%
  select(year, white_includes_white_hispanics, 
         black, asian, hispanic_latino, foreignborn) %>%
  pivot_longer(-year, names_to = "race", values_to = "population") %>%
  transform(population = as.numeric(gsub(",", "", population))) %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>%
  ggplot(aes(x = year, y = population, color = race)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.3, 
                                        height = 0), 
             alpha = 0.5) +
  labs(title = "Change in Demographics Over Time in Manhattan, New York",
       subtitle = "Data Webscrapped From Wikipedia. From 1910-2010.",
       x = "Year",
       y = "Population") +
  theme_classic() +
  scale_color_discrete(name = "Race/Census Categories",
                            labels = c("Asian", "Black", "Foreign Born", 
                                       "Hispanic or Latino", "White")) +
  scale_x_continuous(breaks = c(1910, 1920, 1930, 1940, 1950, 
                                1960, 1970, 1980, 1990, 2000, 2010)) +
  scale_y_continuous(breaks = c(0, 250000, 500000, 750000, 1000000, 1250000,
                                1500000, 1750000, 2000000, 2250000, 2500000),
                     labels = c("0", "250,000", "500,000", "750,000",
                                "1,000,000", "1,250,000", "1,500,000",
                                "1,750,000", "2,000,000", "2,250,000", 
                                "2500000"))

change_over_time_manhattan

manhattan_animated_change <- change_over_time_manhattan +
  transition_reveal(year) +
  labs(title = "Change in Demographics Over Time in Manhattan. Year: {as.integer(frame_along)}")

# anim_save("manhattan_change_animation.gif", path = "shiny/change_over_time_graphs/", 
#          animation = manhattan_animated_change)

```

```{r brooklyn-change-over-time}

options(scipen=5)

brooklyn_website = 'https://en.wikipedia.org/wiki/Demographic_history_of_New_York_City#Brooklyn'

table_brooklyn <- website %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[3]') %>%
  html_table(fill = TRUE) %>%
  clean_names()
  
change_over_time_brooklyn <- table_brooklyn %>%
  select(year, white_includes_white_hispanics, 
         black, asian, hispanic_latino, foreignborn) %>%
  pivot_longer(-year, names_to = "race", values_to = "population") %>%
  transform(population = as.numeric(gsub(",", "", population))) %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>%
  ggplot(aes(x = year, y = population, color = race)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.3, 
                                        height = 0), 
             alpha = 0.5) +
  labs(title = "Change in Demographics Over Time in Brooklyn, New York",
       subtitle = "Data Webscrapped From Wikipedia. From 1910-2010.",
       x = "Year",
       y = "Population") +
  theme_classic() +
  scale_color_discrete(name = "Race/Census Categories",
                            labels = c("Asian", "Black", "Foreign Born", 
                                       "Hispanic or Latino", "White")) +
  scale_x_continuous(breaks = c(1910, 1920, 1930, 1940, 1950, 
                                1960, 1970, 1980, 1990, 2000, 2010)) +
  scale_y_continuous(breaks = c(0, 250000, 500000, 750000, 1000000, 1250000,
                                1500000, 1750000, 2000000, 2250000, 2500000,
                                2750000),
                     labels = c("0", "250,000", "500,000", "750,000",
                                "1,000,000", "1,250,000", "1,500,000",
                                "1,750,000", "2,000,000", "2,250,000", 
                                "2,500,000", "2,750,000"))

change_over_time_brooklyn

brooklyn_animated_change <- change_over_time_brooklyn +
  transition_reveal(year) +
  labs(title = "Change in Demographics Over Time in Brooklyn. Year: {as.integer(frame_along)}")

# anim_save("brooklyn_change_animation.gif", path = "shiny/change_over_time_graphs/", 
#          animation = brooklyn_animated_change)

```
