---
title: "household_income"
author: "Adelson Aguasvivas"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(janitor)
library(sf)
library(rgdal)
library(tidycensus)
library(scales)
library(gt)
library(gridExtra)
library(lemon)
library(rvest)
library(magrittr)
library(leaflet)
library(gganimate)
library(spdplyr)
library(rmapshaper)

household_income_data_1950 <- "raw-data/householdincomedata/1950/nhgis0021_csv/nhgis0021_ds82_1950_tract.csv"
census_tract_1950 <- "raw-data/householdincomedata/1950/nhgis0021_shape/nhgis0021_shapefile_tl2008_us_tract_1950/"
census_tract_layers_1950 <- "US_tract_1950_conflated"

household_income_data_1960 <- "raw-data/householdincomedata/1960/nhgis0022_csv/nhgis0022_ds92_1960_tract.csv"
census_tract_1960 <- "raw-data/householdincomedata/1960/nhgis0022_shape/nhgis0022_shapefile_tl2008_us_tract_1960/"
census_tract_layers_1960 <- "US_tract_1960_conflated"

household_income_data_1970 <- "raw-data/householdincomedata/1970/nhgis0023_csv/nhgis0023_ds99_1970_tract.csv"
census_tract_1970 <- "raw-data/householdincomedata/1970/nhgis0023_shape/nhgis0023_shapefile_tl2008_us_tract_1970/"
census_tract_layers_1970 <- "US_tract_1970_conflated"

household_income_data_1980 <- "raw-data/householdincomedata/1980/nhgis0024_csv/nhgis0024_ds107_1980_tract.csv"
census_tract_1980 <- "raw-data/householdincomedata/1980/nhgis0024_shape/nhgis0024_shapefile_tl2008_us_tract_1980/"
census_tract_layers_1980 <- "US_tract_1980_conflated"

household_income_data_1990 <- "raw-data/householdincomedata/1990/nhgis0025_csv/nhgis0025_ds123_1990_tract.csv"
census_tract_1990 <- "raw-data/householdincomedata/1990/nhgis0025_shape/nhgis0025_shapefile_tl2008_us_tract_1990/"
census_tract_layers_1990 <- "US_tract_1990_conflated"

household_income_data_2000 <- "raw-data/householdincomedata/2000/nhgis0026_csv/nhgis0026_ds151_2000_tract.csv"
census_tract_2000 <- "raw-data/householdincomedata/2000/nhgis0026_shape/nhgis0026_shapefile_tl2008_us_tract_2000/"
census_tract_layers_2000 <- "US_tract_2000_conflated"

household_income_data_2010 <- "raw-data/householdincomedata/2010/nhgis0027_csv/nhgis0027_ds176_20105_2010_tract.csv"
census_tract_2010 <- "raw-data/householdincomedata/2010/nhgis0027_shape/nhgis0027_shapefile_tl2010_us_tract_2010/"
census_tract_layers_2010 <- "US_tract_2010"

```


```{r manhattan-ny1950census, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(household_income_data_1950)%>%
  filter(STATE == "New York" & B0F001 > 0) %>%
  mutate(MedianHHIncome1949 = B0F001) %>%
  select(GISJOIN,MedianHHIncome1949)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_1950,
                          layer = census_tract_layers_1950)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% filter(NHGISST == "360" & COUNTY == "061")%>%
  merge(data1950, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

# Set palette color

write_rds(tracts1950, "shiny/household_income/manhattan/1950/household_income_1950.rds")


pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1949)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1949, opacity = 1.0)



```

```{r manhattan-ny1960census, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960<-read.csv(household_income_data_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B8W001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:23])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:23])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960%>%
                mutate(MedianIncome1960=recode(MedianBracket,"B8W001"=500,"B8W002"=1500, "B8W003"=2500,
                                         "B8W004"=3500, "B8W005"=4500, "B8W006"=5500,
                                         "B8W007"=6500, "B8W008"=7500, "B8W009"=8500,
                                         "B8W010"=9500, "B8W011"=12500, "B8W012"=20000,
                                         "B8W013"=25000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

manhattan_household_income_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "61" & !is.na(MedianIncome1960)) %>%
  select(GISJOIN, MedianIncome1960)

manhattan_1960_map <- sf::st_read(dsn = census_tract_1960,
                        layer = census_tract_layers_1960)

manhattan_1960_map <- manhattan_1960_map %>%
  merge(manhattan_household_income_1960, "GISJOIN")

manhattan_1960_map <- sf::st_transform(manhattan_1960_map,  
                                       crs="+init=epsg:4326")

manhattan_1960_map <- rmapshaper::ms_simplify(manhattan_1960_map)

# Set palette color

write_rds(manhattan_1960_map, "shiny/household_income/manhattan/1960/household_income_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(manhattan_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1960)) %>%
  addLegend(pal = pal, values = ~MedianIncome1960, opacity = 1.0)


```

```{r manhattan-ny1970census, include=FALSE}

#### Median Family Income 1970 Census Tracts####
tracts1970 <- read.csv(household_income_data_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(C3T001)==FALSE & C3T001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:30])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:30])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianIncome1970=recode(MedianBracket,"C3T001"=500,"C3T002"=1500, "C3T003"=2500,
                             "C3T004"=3500, "C3T005"=4500, "C3T006"=5500,
                             "C3T007"=6500, "C3T008"=7500, "C3T009"=8500,
                             "C3T010"=9500, "C3T011"=11000, "C3T012"=13500,
                             "C3T013"=20000, "C3T014"=37500, "C3T015"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

manhattan_household_income_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "61" & !is.na(MedianIncome1970)) %>%
  select(GISJOIN, MedianIncome1970)

manhattan_1970_map <- sf::st_read(dsn = census_tract_1970,
                        layer = census_tract_layers_1970)

manhattan_1970_map <- manhattan_1970_map %>%
  merge(manhattan_household_income_1970, "GISJOIN")

manhattan_1970_map <- sf::st_transform(manhattan_1970_map,  
                                       crs="+init=epsg:4326")

manhattan_1970_map <- rmapshaper::ms_simplify(manhattan_1970_map)

# Set palette color

write_rds(manhattan_1970_map, "shiny/household_income/manhattan/1970/household_income_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(manhattan_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1970)) %>%
  addLegend(pal = pal, values = ~MedianIncome1970, opacity = 1.0)


```

```{r manhattan-ny1980census, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

manhattandata1980 <- 
  read.csv(household_income_data_1980) %>%
  filter(STATE == "New York" & DIE001 > 0) %>%
  mutate(MedianHHIncome1979 = DIE001) %>%
  select(GISJOIN, MedianHHIncome1979)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_1980,
                         layer = census_tract_layers_1980)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="061")%>%
  merge(manhattandata1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980, crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/household_income/manhattan/1980/household_income_1980.rds")

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1979)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1979, opacity = 1.0)



```

```{r manhattan-ny1990census, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(household_income_data_1990)%>%
  filter(STATE == "New York" & E4U001 > 0)%>%
  mutate(MedianHHIncome1989 = E4U001)%>%
  select(GISJOIN,MedianHHIncome1989)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_1990,
                         layer = census_tract_layers_1990)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="061") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326") 

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/household_income/manhattan/1990/household_income_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1989)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1989, opacity = 1.0)



```

```{r manhattan-ny2000census, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(household_income_data_2000)%>%
  filter(STATE == "New York" & GMY001 > 0)%>%
  mutate(MedianHHIncome1999 = GMY001)%>%
  select(GISJOIN,MedianHHIncome1999)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_2000,
                         layer = census_tract_layers_2000)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="061") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <-sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/household_income/manhattan/2000/household_income_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data


leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1999)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1999, opacity = 1.0)



```

```{r manhattan-ny2010census, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(household_income_data_2010)%>%
  filter(STATE == "New York" & JOIM001 > 0)%>%
  mutate(MedianHHIncome2010 = JOIM001)%>%
  select(GISJOIN,MedianHHIncome2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_2010,
                         layer = census_tract_layers_2010)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10 == "061")%>%
  merge(data2010, "GISJOIN")

# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <-sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/household_income/manhattan/2010/household_income_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome2010)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome2010, opacity = 1.0)


```


BRONX HOUSEHOLD INCOME 


```{r bronx-income-1950, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

bronx_data1950 <- read.csv(household_income_data_1950)%>%
  filter(STATE == "New York" & B0F001 > 0) %>%
  mutate(MedianHHIncome1949 = B0F001) %>%
  select(GISJOIN,MedianHHIncome1949)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

bronx_tracts1950 <- sf::st_read(dsn = census_tract_1950,
                                layer = census_tract_layers_1950)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

bronx_tracts1950 <-
  bronx_tracts1950 %>% filter(NHGISST == "360" & COUNTY == "005") %>%
  merge(bronx_data1950, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

bronx_tracts1950 <- sf::st_transform(bronx_tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

bronx_tracts1950 <- rmapshaper::ms_simplify(bronx_tracts1950)

# Set palette color

write_rds(bronx_tracts1950, "shiny/household_income/bronx/1950/household_income_1950.rds")


pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(bronx_tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1949)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1949, opacity = 1.0)



```

```{r bronx-income-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960<-read.csv(household_income_data_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B8W001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:23])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:23])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianIncome1960=recode(MedianBracket,"B8W001"=500,"B8W002"=1500, "B8W003"=2500,
                                         "B8W004"=3500, "B8W005"=4500, "B8W006"=5500,
                                         "B8W007"=6500, "B8W008"=7500, "B8W009"=8500,
                                         "B8W010"=9500, "B8W011"=12500, "B8W012"=20000,
                                         "B8W013"=25000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

bronx_household_income_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "5" & !is.na(MedianIncome1960)) %>%
  select(GISJOIN, MedianIncome1960)

bronx_1960_map <- sf::st_read(dsn = census_tract_1960,
                        layer = census_tract_layers_1960)

bronx_1960_map <- bronx_1960_map %>%
  merge(bronx_household_income_1960, "GISJOIN")

bronx_1960_map <- sf::st_transform(bronx_1960_map,  
                                       crs="+init=epsg:4326")

bronx_1960_map <- rmapshaper::ms_simplify(bronx_1960_map)

# Set palette color

write_rds(bronx_1960_map, "shiny/household_income/bronx/1960/household_income_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(bronx_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1960)) %>%
  addLegend(pal = pal, values = ~MedianIncome1960, opacity = 1.0)

```

```{r bronx-income-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(household_income_data_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(C3T001)==FALSE & C3T001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:30])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:30])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print<-tracts1970 %>%
  mutate(MedianIncome1970=recode(MedianBracket,"C3T001"=500,"C3T002"=1500, "C3T003"=2500,
                             "C3T004"=3500, "C3T005"=4500, "C3T006"=5500,
                             "C3T007"=6500, "C3T008"=7500, "C3T009"=8500,
                             "C3T010"=9500, "C3T011"=11000, "C3T012"=13500,
                             "C3T013"=20000, "C3T014"=37500, "C3T015"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

bronx_household_income_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "5" & !is.na(MedianIncome1970)) %>%
  select(GISJOIN, MedianIncome1970)

bronx_1970_map <- sf::st_read(dsn = census_tract_1970,
                        layer = census_tract_layers_1970)

bronx_1970_map <- bronx_1970_map %>%
  merge(bronx_household_income_1970, "GISJOIN")

bronx_1970_map <- sf::st_transform(bronx_1970_map,  
                                       crs="+init=epsg:4326")

bronx_1970_map <- rmapshaper::ms_simplify(bronx_1970_map)

# Set palette color

write_rds(bronx_1970_map, "shiny/household_income/bronx/1970/household_income_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(bronx_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1970)) %>%
  addLegend(pal = pal, values = ~MedianIncome1970, opacity = 1.0)


```

```{r bronx-income-1980, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

bronxdata1980 <- 
  read.csv(household_income_data_1980) %>%
  filter(STATE == "New York" & DIE001 > 0) %>%
  mutate(MedianHHIncome1979 = DIE001) %>%
  select(GISJOIN, MedianHHIncome1979)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_1980,
                         layer = census_tract_layers_1980)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="005")%>%
  merge(bronxdata1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980, crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/household_income/bronx/1980/household_income_1980.rds")

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1979)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1979, opacity = 1.0)



```

```{r bronx-income-1990, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(household_income_data_1990)%>%
  filter(STATE == "New York" & E4U001 > 0)%>%
  mutate(MedianHHIncome1989 = E4U001)%>%
  select(GISJOIN,MedianHHIncome1989)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_1990,
                         layer = census_tract_layers_1990)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="005")%>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/household_income/bronx/1990/household_income_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1989)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1989, opacity = 1.0)



```

```{r bronx-income-2000, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(household_income_data_2000)%>%
  filter(STATE == "New York" & GMY001 > 0)%>%
  mutate(MedianHHIncome1999 = GMY001)%>%
  select(GISJOIN,MedianHHIncome1999)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_2000,
                         layer = census_tract_layers_2000)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="005")%>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <-sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/household_income/bronx/2000/household_income_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data


leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1999)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1999, opacity = 1.0)



```

```{r bronx-income-2010, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(household_income_data_2010)%>%
  filter(STATE == "New York" & JOIM001 > 0)%>%
  mutate(MedianHHIncome2010 = JOIM001)%>%
  select(GISJOIN,MedianHHIncome2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_2010,
                         layer = census_tract_layers_2010)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="005")%>%
  merge(data2010, "GISJOIN")

# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <-sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/household_income/bronx/2010/household_income_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome2010)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome2010, opacity = 1.0)


```



BROOKLYN HOUSEHOLD INCOME 


```{r brooklyn-income-1950, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

brooklyn_data1950 <- read.csv(household_income_data_1950)%>%
  filter(STATE == "New York" & B0F001 > 0) %>%
  mutate(MedianHHIncome1949 = B0F001) %>%
  select(GISJOIN,MedianHHIncome1949)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

brooklyn_tracts1950 <- sf::st_read(dsn = census_tract_1950,
                                layer = census_tract_layers_1950)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

brooklyn_tracts1950 <-
  brooklyn_tracts1950 %>% filter(NHGISST == "360" & COUNTY == "047") %>%
  merge(brooklyn_data1950, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

brooklyn_tracts1950 <- sf::st_transform(brooklyn_tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

brooklyn_tracts1950 <- rmapshaper::ms_simplify(brooklyn_tracts1950)

# Set palette color

write_rds(brooklyn_tracts1950, "shiny/household_income/brooklyn/1950/household_income_1950.rds")


pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(brooklyn_tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1949)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1949, opacity = 1.0)



```

```{r brooklyn-income-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960<-read.csv(household_income_data_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B8W001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:23])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:23])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianIncome1960=recode(MedianBracket,"B8W001"=500,"B8W002"=1500, "B8W003"=2500,
                                         "B8W004"=3500, "B8W005"=4500, "B8W006"=5500,
                                         "B8W007"=6500, "B8W008"=7500, "B8W009"=8500,
                                         "B8W010"=9500, "B8W011"=12500, "B8W012"=20000,
                                         "B8W013"=25000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

brooklyn_household_income_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "47" & !is.na(MedianIncome1960)) %>%
  select(GISJOIN, MedianIncome1960)

brooklyn_1960_map <- sf::st_read(dsn = census_tract_1960,
                        layer = census_tract_layers_1960)

brooklyn_1960_map <- brooklyn_1960_map %>%
  merge(brooklyn_household_income_1960, "GISJOIN")

brooklyn_1960_map <- sf::st_transform(brooklyn_1960_map,  
                                       crs="+init=epsg:4326")

brooklyn_1960_map <- rmapshaper::ms_simplify(brooklyn_1960_map)

# Set palette color

write_rds(brooklyn_1960_map, "shiny/household_income/brooklyn/1960/household_income_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(brooklyn_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1960)) %>%
  addLegend(pal = pal, values = ~MedianIncome1960, opacity = 1.0)

```

```{r brooklyn-income-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(household_income_data_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(C3T001)==FALSE & C3T001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:30])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:30])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <-tracts1970 %>%
  mutate(MedianIncome1970=recode(MedianBracket,"C3T001"=500,"C3T002"=1500, "C3T003"=2500,
                             "C3T004"=3500, "C3T005"=4500, "C3T006"=5500,
                             "C3T007"=6500, "C3T008"=7500, "C3T009"=8500,
                             "C3T010"=9500, "C3T011"=11000, "C3T012"=13500,
                             "C3T013"=20000, "C3T014"=37500, "C3T015"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

brooklyn_household_income_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "47" & !is.na(MedianIncome1970)) %>%
  select(GISJOIN, MedianIncome1970)

brooklyn_1970_map <- sf::st_read(dsn = census_tract_1970,
                        layer = census_tract_layers_1970)

brooklyn_1970_map <- brooklyn_1970_map %>%
  merge(brooklyn_household_income_1970, "GISJOIN")

brooklyn_1970_map <- sf::st_transform(brooklyn_1970_map,  
                                       crs="+init=epsg:4326")

brooklyn_1970_map <- rmapshaper::ms_simplify(brooklyn_1970_map)

# Set palette color

write_rds(brooklyn_1970_map, "shiny/household_income/brooklyn/1970/household_income_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(brooklyn_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1970)) %>%
  addLegend(pal = pal, values = ~MedianIncome1970, opacity = 1.0)


```

```{r brooklyn-income-1980, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

brooklyndata1980 <- 
  read.csv(household_income_data_1980) %>%
  filter(STATE == "New York" & DIE001 > 0) %>%
  mutate(MedianHHIncome1979 = DIE001) %>%
  select(GISJOIN, MedianHHIncome1979)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_1980,
                         layer = census_tract_layers_1980)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="047")%>%
  merge(brooklyndata1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980, crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/household_income/brooklyn/1980/household_income_1980.rds")

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1979)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1979, opacity = 1.0)



```

```{r brooklyn-income-1990, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(household_income_data_1990)%>%
  filter(STATE == "New York" & E4U001 > 0)%>%
  mutate(MedianHHIncome1989 = E4U001) %>%
  select(GISJOIN,MedianHHIncome1989)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_1990,
                         layer = census_tract_layers_1990)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="047") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/household_income/brooklyn/1990/household_income_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1989)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1989, opacity = 1.0)



```

```{r brooklyn-income-2000, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(household_income_data_2000) %>%
  filter(STATE == "New York" & GMY001 > 0) %>%
  mutate(MedianHHIncome1999 = GMY001) %>%
  select(GISJOIN,MedianHHIncome1999)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_2000,
                         layer = census_tract_layers_2000)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="047") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <-sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/household_income/brooklyn/2000/household_income_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data


leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1999)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1999, opacity = 1.0)



```

```{r brooklyn-income-2010, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(household_income_data_2010) %>%
  filter(STATE == "New York" & JOIM001 > 0) %>%
  mutate(MedianHHIncome2010 = JOIM001) %>%
  select(GISJOIN,MedianHHIncome2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_2010,
                         layer = census_tract_layers_2010)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="047")%>%
  merge(data2010, "GISJOIN")

# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <-sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/household_income/brooklyn/2010/household_income_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome2010)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome2010, opacity = 1.0)


```


QUEENS HOUSEHOLD INCOME 


```{r queens-income-1950, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

queens_data1950 <- read.csv(household_income_data_1950) %>%
  filter(STATE == "New York" & B0F001 > 0) %>%
  mutate(MedianHHIncome1949 = B0F001) %>%
  select(GISJOIN,MedianHHIncome1949)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

queens_tracts1950 <- sf::st_read(dsn = census_tract_1950,
                                layer = census_tract_layers_1950)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

queens_tracts1950 <-
  queens_tracts1950 %>% filter(NHGISST == "360" & COUNTY == "081") %>%
  merge(queens_data1950, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

queens_tracts1950 <- sf::st_transform(queens_tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

queens_tracts1950 <- rmapshaper::ms_simplify(queens_tracts1950)

# Set palette color

write_rds(queens_tracts1950, "shiny/household_income/queens/1950/household_income_1950.rds")


pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(queens_tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1949)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1949, opacity = 1.0)



```

```{r queens-income-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960<-read.csv(household_income_data_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B8W001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:23])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:23])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianIncome1960=recode(MedianBracket,"B8W001"=500,"B8W002"=1500, "B8W003"=2500,
                                         "B8W004"=3500, "B8W005"=4500, "B8W006"=5500,
                                         "B8W007"=6500, "B8W008"=7500, "B8W009"=8500,
                                         "B8W010"=9500, "B8W011"=12500, "B8W012"=20000,
                                         "B8W013"=25000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

queens_household_income_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "81" & !is.na(MedianIncome1960)) %>%
  select(GISJOIN, MedianIncome1960)

queens_1960_map <- sf::st_read(dsn = census_tract_1960,
                        layer = census_tract_layers_1960)

queens_1960_map <- queens_1960_map %>%
  merge(queens_household_income_1960, "GISJOIN")

queens_1960_map <- sf::st_transform(queens_1960_map,  
                                       crs="+init=epsg:4326")

queens_1960_map <- rmapshaper::ms_simplify(queens_1960_map)

# Set palette color

write_rds(queens_1960_map, "shiny/household_income/queens/1960/household_income_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(queens_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1960)) %>%
  addLegend(pal = pal, values = ~MedianIncome1960, opacity = 1.0)

```

```{r queens-income-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(household_income_data_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(C3T001)==FALSE & C3T001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:30])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:30])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <-tracts1970 %>%
  mutate(MedianIncome1970=recode(MedianBracket,"C3T001"=500,"C3T002"=1500, "C3T003"=2500,
                             "C3T004"=3500, "C3T005"=4500, "C3T006"=5500,
                             "C3T007"=6500, "C3T008"=7500, "C3T009"=8500,
                             "C3T010"=9500, "C3T011"=11000, "C3T012"=13500,
                             "C3T013"=20000, "C3T014"=37500, "C3T015"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

queens_household_income_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "81" & !is.na(MedianIncome1970)) %>%
  select(GISJOIN, MedianIncome1970)

queens_1970_map <- sf::st_read(dsn = census_tract_1970,
                        layer = census_tract_layers_1970)

queens_1970_map <- queens_1970_map %>%
  merge(queens_household_income_1970, "GISJOIN")

queens_1970_map <- sf::st_transform(queens_1970_map,  
                                       crs="+init=epsg:4326")

queens_1970_map <- rmapshaper::ms_simplify(queens_1970_map)

# Set palette color

write_rds(queens_1970_map, "shiny/household_income/queens/1970/household_income_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(queens_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome1970)) %>%
  addLegend(pal = pal, values = ~MedianIncome1970, opacity = 1.0)


```

```{r queens-income-1980, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

queensdata1980 <- 
  read.csv(household_income_data_1980) %>%
  filter(STATE == "New York" & DIE001 > 0) %>%
  mutate(MedianHHIncome1979 = DIE001) %>%
  select(GISJOIN, MedianHHIncome1979)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_1980,
                         layer = census_tract_layers_1980)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="081")%>%
  merge(queensdata1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980, crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/household_income/queens/1980/household_income_1980.rds")

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1979)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1979, opacity = 1.0)



```

```{r queens-income-1990, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(household_income_data_1990)%>%
  filter(STATE == "New York" & E4U001 > 0)%>%
  mutate(MedianHHIncome1989 = E4U001) %>%
  select(GISJOIN,MedianHHIncome1989)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_1990,
                         layer = census_tract_layers_1990)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="081") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/household_income/queens/1990/household_income_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1989)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1989, opacity = 1.0)



```

```{r queens-income-2000, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(household_income_data_2000) %>%
  filter(STATE == "New York" & GMY001 > 0) %>%
  mutate(MedianHHIncome1999 = GMY001) %>%
  select(GISJOIN,MedianHHIncome1999)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_2000,
                         layer = census_tract_layers_2000)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="081") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <-sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/household_income/queens/2000/household_income_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data


leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1999)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1999, opacity = 1.0)



```

```{r queens-income-2010, include=FALSE}

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(household_income_data_2010) %>%
  filter(STATE == "New York" & JOIM001 > 0) %>%
  mutate(MedianHHIncome2010 = JOIM001) %>%
  select(GISJOIN,MedianHHIncome2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_2010,
                         layer = census_tract_layers_2010)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="081") %>%
  merge(data2010, "GISJOIN")

# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <-sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/household_income/queens/2010/household_income_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome2010)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome2010, opacity = 1.0)


```










