---
title: "house_value"
author: "Adelson Aguasvivas"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(sf)
library(rgdal)
library(tidycensus)
library(scales)
library(gt)
library(gridExtra)
library(lemon)
library(rvest)
library(magrittr)
library(leaflet)
library(gganimate)
library(spdplyr)
library(rmapshaper)

housing_value_1950 <- "raw-data/housingdata/1950/nhgis0028_csv/nhgis0028_ds82_1950_tract.csv"
census_tract_housing_value_1950 <- "raw-data/housingdata/1950/nhgis0028_shape/nhgis0028_shapefile_tl2008_us_tract_1950/"
census_tract_housing_value_1950_layers <- "US_tract_1950_conflated"

housing_value_1960 <- "raw-data/housingdata/1960/nhgis0031_csv/nhgis0031_ds92_1960_tract.csv"
census_tract_housing_value_1960 <- "raw-data/housingdata/1960/nhgis0031_shape/nhgis0031_shapefile_tl2008_us_tract_1960/"
census_tract_housing_value_1960_layers <- "US_tract_1960_conflated"

housing_value_1970 <- "raw-data/housingdata/1970/nhgis0032_csv/nhgis0032_ds95_1970_tract.csv"
census_tract_housing_value_1970 <- "raw-data/housingdata/1970/nhgis0032_shape/nhgis0032_shapefile_tl2008_us_tract_1970/"
census_tract_housing_value_1970_layers <- "US_tract_1970_conflated"

housing_value_1980 <- "raw-data/housingdata/1980/nhgis0029_csv/nhgis0029_ds104_1980_tract.csv"
census_tract_housing_value_1980 <- "raw-data/housingdata/1980/nhgis0029_shape/nhgis0029_shapefile_tl2008_us_tract_1980/"
census_tract_housing_value_1980_layers <- "US_tract_1980_conflated"

housing_value_1990 <- "raw-data/housingdata/1990/nhgis0030_csv/nhgis0030_ds120_1990_tract.csv"
census_tract_housing_value_1990 <- "raw-data/housingdata/1990/nhgis0030_shape/nhgis0030_shapefile_tl2008_us_tract_1990/"
census_tract_housing_value_1990_layers <- "US_tract_1990_conflated"

housing_value_2000 <- "raw-data/housingdata/2000/nhgis0033_csv/nhgis0033_ds151_2000_tract.csv"
census_tract_housing_value_2000 <- "raw-data/housingdata/2000/nhgis0033_shape/nhgis0033_shapefile_tl2008_us_tract_2000/"
census_tract_housing_value_2000_layers <- "US_tract_2000_conflated"

housing_value_2010 <- "raw-data/housingdata/2010/nhgis0034_csv/nhgis0034_ds176_20105_2010_tract.csv"
census_tract_housing_value_2010 <- "raw-data/housingdata/2010/nhgis0034_shape/nhgis0034_shapefile_tl2010_us_tract_2010/"
census_tract_housing_value_2010_layers <- "US_tract_2010"

```

```{r manhattan-housing-value-1950, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(housing_value_1950) %>%
  filter(STATE == "New York" & B09001 > 0) %>%
  mutate(HousingValue1950 = B09001)%>%
  select(GISJOIN, HousingValue1950)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_housing_value_1950,
                         layer = census_tract_housing_value_1950_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% 
  merge(data1950, "GISJOIN") %>%
  filter(NHGISST == "360") 
  


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

write_rds(tracts1950, "shiny/housing_value/manhattan/1950/housing_value_1950.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1950)) %>%
  addLegend(pal = pal, values = ~HousingValue1950, opacity = 1.0)




```

```{r manhattan-housing-value-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960 <- read.csv(housing_value_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B7O001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:20])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:20])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianHousingValue1960=recode(MedianBracket,"B7O001"=2500,"B7O002"=6200, "B7O003"=8700,
                                         "B7O004"=11200, "B7O005"=13700, "B7O006"=16200,
                                         "B7O007"=18700, "B7O008"=22450, "B7O009"=29950,
                                         "B7O010"=35000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

manhattan_housing_value_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "61" & !is.na(MedianHousingValue1960)) %>%
  select(GISJOIN, MedianHousingValue1960)

manhattan_1960_map <- sf::st_read(dsn = census_tract_housing_value_1960,
                        layer = census_tract_housing_value_1960_layers)

manhattan_1960_map <- manhattan_1960_map %>%
  merge(manhattan_housing_value_1960, "GISJOIN")

manhattan_1960_map <- sf::st_transform(manhattan_1960_map,  
                                       crs="+init=epsg:4326")

manhattan_1960_map <- rmapshaper::ms_simplify(manhattan_1960_map)

# Set palette color

write_rds(manhattan_1960_map, "shiny/housing_value/manhattan/1960/housing_value_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(manhattan_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1960)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1960, opacity = 1.0)


```

```{r manhattan-housing-value-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(housing_value_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(CG7001)==FALSE & CG7001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:26])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:26])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianHousingValue1970=recode(MedianBracket,"CG7001"=2500,"CG7002"=6250, "CG7003"=8750,
                             "CG7004"=11250, "CG7005"=13750, "CG7006"=16250,
                             "CG7007"=18750, "CG7008"=22500, "CG7009"=30000,
                             "CG7010"=42500, "CG7011"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

tracts1970Print

manhattan_housing_value_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "61" & !is.na(MedianHousingValue1970)) %>%
  select(GISJOIN, MedianHousingValue1970)

manhattan_1970_map <- sf::st_read(dsn = census_tract_housing_value_1970,
                        layer = census_tract_housing_value_1970_layers)

manhattan_1970_map <- manhattan_1970_map %>%
  merge(manhattan_housing_value_1970, "GISJOIN")

manhattan_1970_map <- sf::st_transform(manhattan_1970_map,  
                                       crs="+init=epsg:4326")

# manhattan_1970_map <- rmapshaper::ms_simplify(manhattan_1970_map)

# Set palette color

write_rds(manhattan_1970_map, "shiny/housing_value/manhattan/1970/housing_value_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(manhattan_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1970)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1970, opacity = 1.0)


```

```{r manhattan-housing-value-1980, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1980 <- read.csv(housing_value_1980) %>%
  filter(STATE == "New York" & C8J001 > 0) %>%
  mutate(HousingValue1980 = C8J001) %>%
  select(GISJOIN, HousingValue1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_housing_value_1980,
                         layer = census_tract_housing_value_1980_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="061") %>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/housing_value/manhattan/1980/housing_value_1980.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1980)) %>%
  addLegend(pal = pal, values = ~HousingValue1980, opacity = 1.0)

```

```{r manhattan-housing-value-1990, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(housing_value_1990) %>%
  filter(STATE == "New York" & EST001 > 0) %>%
  mutate(HousingValue1990 = EST001) %>%
  select(GISJOIN, HousingValue1990)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_housing_value_1990,
                         layer = census_tract_housing_value_1990_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="061") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/housing_value/manhattan/1990/housing_value_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1990)) %>%
  addLegend(pal = pal, values = ~HousingValue1990, opacity = 1.0)


```

```{r manhattan-housing-value-2000, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(housing_value_2000) %>%
  filter(STATE == "New York" & GB7001 > 0) %>%
  mutate(HousingValue2000 = GB7001) %>%
  select(GISJOIN, HousingValue2000)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_housing_value_2000,
                         layer = census_tract_housing_value_2000_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="061") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <- sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/housing_value/manhattan/2000/housing_value_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2000)) %>%
  addLegend(pal = pal, values = ~HousingValue2000, opacity = 1.0)


```

```{r manhattan-housing-value-2010, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(housing_value_2010) %>%
  filter(STATE == "New York" & JTIE001 > 0) %>%
  mutate(HousingValue2010 = JTIE001) %>%
  select(GISJOIN, HousingValue2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_housing_value_2010,
                         layer = census_tract_housing_value_2010_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="061") %>%
  merge(data2010, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <- sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/housing_value/manhattan/2010/housing_value_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2010)) %>%
  addLegend(pal = pal, values = ~HousingValue2010, opacity = 1.0)


```

BRONX HOUSING VALUE


```{r bronx-housing-value-1950, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(housing_value_1950) %>%
  filter(STATE == "New York" & B09001 > 0) %>%
  mutate(HousingValue1950 = B09001)%>%
  select(GISJOIN, HousingValue1950)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_housing_value_1950,
                         layer = census_tract_housing_value_1950_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% 
  merge(data1950, "GISJOIN") %>%
  filter(NHGISST == "360" & COUNTY == "005") 
  


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

write_rds(tracts1950, "shiny/housing_value/bronx/1950/housing_value_1950.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1950)) %>%
  addLegend(pal = pal, values = ~HousingValue1950, opacity = 1.0)




```

```{r bronx-housing-value-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960 <- read.csv(housing_value_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B7O001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:20])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:20])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianHousingValue1960=recode(MedianBracket,"B7O001"=2500,"B7O002"=6200, "B7O003"=8700,
                                         "B7O004"=11200, "B7O005"=13700, "B7O006"=16200,
                                         "B7O007"=18700, "B7O008"=22450, "B7O009"=29950,
                                         "B7O010"=35000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

bronx_housing_value_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "5" & !is.na(MedianHousingValue1960)) %>%
  select(GISJOIN, MedianHousingValue1960)

bronx_1960_map <- sf::st_read(dsn = census_tract_housing_value_1960,
                        layer = census_tract_housing_value_1960_layers)

bronx_1960_map <- bronx_1960_map %>%
  merge(bronx_housing_value_1960, "GISJOIN")

bronx_1960_map <- sf::st_transform(bronx_1960_map,  
                                       crs="+init=epsg:4326")

bronx_1960_map <- rmapshaper::ms_simplify(bronx_1960_map)

# Set palette color

write_rds(bronx_1960_map, "shiny/housing_value/bronx/1960/housing_value_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(bronx_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1960)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1960, opacity = 1.0)


```

```{r bronx-housing-value-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(housing_value_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(CG7001)==FALSE & CG7001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:26])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:26])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianHousingValue1970=recode(MedianBracket,"CG7001"=2500,"CG7002"=6250, "CG7003"=8750,
                             "CG7004"=11250, "CG7005"=13750, "CG7006"=16250,
                             "CG7007"=18750, "CG7008"=22500, "CG7009"=30000,
                             "CG7010"=42500, "CG7011"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

tracts1970Print

bronx_housing_value_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "5" & !is.na(MedianHousingValue1970)) %>%
  select(GISJOIN, MedianHousingValue1970)

bronx_1970_map <- sf::st_read(dsn = census_tract_housing_value_1970,
                        layer = census_tract_housing_value_1970_layers)

bronx_1970_map <- bronx_1970_map %>%
  merge(bronx_housing_value_1970, "GISJOIN")

bronx_1970_map <- sf::st_transform(bronx_1970_map,  
                                       crs="+init=epsg:4326")

bronx_1970_map <- rmapshaper::ms_simplify(bronx_1970_map)

# Set palette color

write_rds(bronx_1970_map, "shiny/housing_value/bronx/1970/housing_value_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(bronx_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1970)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1970, opacity = 1.0)


```

```{r bronx-housing-value-1980, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1980 <- read.csv(housing_value_1980) %>%
  filter(STATE == "New York" & C8J001 > 0) %>%
  mutate(HousingValue1980 = C8J001) %>%
  select(GISJOIN, HousingValue1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_housing_value_1980,
                         layer = census_tract_housing_value_1980_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="005") %>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/housing_value/bronx/1980/housing_value_1980.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1980)) %>%
  addLegend(pal = pal, values = ~HousingValue1980, opacity = 1.0)

```

```{r bronx-housing-value-1990, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(housing_value_1990) %>%
  filter(STATE == "New York" & EST001 > 0) %>%
  mutate(HousingValue1990 = EST001) %>%
  select(GISJOIN, HousingValue1990)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_housing_value_1990,
                         layer = census_tract_housing_value_1990_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="005") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/housing_value/bronx/1990/housing_value_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1990)) %>%
  addLegend(pal = pal, values = ~HousingValue1990, opacity = 1.0)


```

```{r bronx-housing-value-2000, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(housing_value_2000) %>%
  filter(STATE == "New York" & GB7001 > 0) %>%
  mutate(HousingValue2000 = GB7001) %>%
  select(GISJOIN, HousingValue2000)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_housing_value_2000,
                         layer = census_tract_housing_value_2000_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="005") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <- sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/housing_value/bronx/2000/housing_value_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2000)) %>%
  addLegend(pal = pal, values = ~HousingValue2000, opacity = 1.0)


```

```{r bronx-housing-value-2010, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(housing_value_2010) %>%
  filter(STATE == "New York" & JTIE001 > 0) %>%
  mutate(HousingValue2010 = JTIE001) %>%
  select(GISJOIN, HousingValue2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_housing_value_2010,
                         layer = census_tract_housing_value_2010_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="005") %>%
  merge(data2010, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <- sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/housing_value/bronx/2010/housing_value_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2010)) %>%
  addLegend(pal = pal, values = ~HousingValue2010, opacity = 1.0)


```


BROOKLYN HOUSING VALUE


```{r brooklyn-housing-value-1950, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(housing_value_1950) %>%
  filter(STATE == "New York" & B09001 > 0) %>%
  mutate(HousingValue1950 = B09001)%>%
  select(GISJOIN, HousingValue1950)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_housing_value_1950,
                         layer = census_tract_housing_value_1950_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% 
  merge(data1950, "GISJOIN") %>%
  filter(NHGISST == "360" & COUNTY == "047") 
  


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

write_rds(tracts1950, "shiny/housing_value/brooklyn/1950/housing_value_1950.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1950)) %>%
  addLegend(pal = pal, values = ~HousingValue1950, opacity = 1.0)




```

```{r brooklyn-housing-value-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960 <- read.csv(housing_value_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B7O001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:20])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:20])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianHousingValue1960=recode(MedianBracket,"B7O001"=2500,"B7O002"=6200, "B7O003"=8700,
                                         "B7O004"=11200, "B7O005"=13700, "B7O006"=16200,
                                         "B7O007"=18700, "B7O008"=22450, "B7O009"=29950,
                                         "B7O010"=35000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

brooklyn_housing_value_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "47" & !is.na(MedianHousingValue1960)) %>%
  select(GISJOIN, MedianHousingValue1960)

brooklyn_1960_map <- sf::st_read(dsn = census_tract_housing_value_1960,
                        layer = census_tract_housing_value_1960_layers)

brooklyn_1960_map <- brooklyn_1960_map %>%
  merge(brooklyn_housing_value_1960, "GISJOIN")

brooklyn_1960_map <- sf::st_transform(brooklyn_1960_map,  
                                       crs="+init=epsg:4326")

brooklyn_1960_map <- rmapshaper::ms_simplify(brooklyn_1960_map)

# Set palette color

write_rds(brooklyn_1960_map, "shiny/housing_value/brooklyn/1960/housing_value_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(brooklyn_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1960)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1960, opacity = 1.0)


```

```{r brooklyn-housing-value-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(housing_value_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(CG7001)==FALSE & CG7001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:26])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:26])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianHousingValue1970=recode(MedianBracket,"CG7001"=2500,"CG7002"=6250, "CG7003"=8750,
                             "CG7004"=11250, "CG7005"=13750, "CG7006"=16250,
                             "CG7007"=18750, "CG7008"=22500, "CG7009"=30000,
                             "CG7010"=42500, "CG7011"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

tracts1970Print

brooklyn_housing_value_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "47" & !is.na(MedianHousingValue1970)) %>%
  select(GISJOIN, MedianHousingValue1970)

brooklyn_1970_map <- sf::st_read(dsn = census_tract_housing_value_1970,
                        layer = census_tract_housing_value_1970_layers)

brooklyn_1970_map <- brooklyn_1970_map %>%
  merge(brooklyn_housing_value_1970, "GISJOIN")

brooklyn_1970_map <- sf::st_transform(brooklyn_1970_map,  
                                       crs="+init=epsg:4326")

brooklyn_1970_map <- rmapshaper::ms_simplify(brooklyn_1970_map)

# Set palette color

write_rds(brooklyn_1970_map, "shiny/housing_value/brooklyn/1970/housing_value_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(brooklyn_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1970)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1970, opacity = 1.0)


```

```{r brooklyn-housing-value-1980, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1980 <- read.csv(housing_value_1980) %>%
  filter(STATE == "New York" & C8J001 > 0) %>%
  mutate(HousingValue1980 = C8J001) %>%
  select(GISJOIN, HousingValue1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_housing_value_1980,
                         layer = census_tract_housing_value_1980_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="047") %>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/housing_value/brooklyn/1980/housing_value_1980.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1980)) %>%
  addLegend(pal = pal, values = ~HousingValue1980, opacity = 1.0)

```

```{r brooklyn-housing-value-1990, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(housing_value_1990) %>%
  filter(STATE == "New York" & EST001 > 0) %>%
  mutate(HousingValue1990 = EST001) %>%
  select(GISJOIN, HousingValue1990)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_housing_value_1990,
                         layer = census_tract_housing_value_1990_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="047") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/housing_value/brooklyn/1990/housing_value_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1990)) %>%
  addLegend(pal = pal, values = ~HousingValue1990, opacity = 1.0)


```

```{r brooklyn-housing-value-2000, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(housing_value_2000) %>%
  filter(STATE == "New York" & GB7001 > 0) %>%
  mutate(HousingValue2000 = GB7001) %>%
  select(GISJOIN, HousingValue2000)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_housing_value_2000,
                         layer = census_tract_housing_value_2000_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="047") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <- sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/housing_value/brooklyn/2000/housing_value_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2000)) %>%
  addLegend(pal = pal, values = ~HousingValue2000, opacity = 1.0)


```

```{r brooklyn-housing-value-2010, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(housing_value_2010) %>%
  filter(STATE == "New York" & JTIE001 > 0) %>%
  mutate(HousingValue2010 = JTIE001) %>%
  select(GISJOIN, HousingValue2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_housing_value_2010,
                         layer = census_tract_housing_value_2010_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="047") %>%
  merge(data2010, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <- sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/housing_value/brooklyn/2010/housing_value_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2010)) %>%
  addLegend(pal = pal, values = ~HousingValue2010, opacity = 1.0)


```


QUEENS HOUSING VALUE


```{r queens-housing-value-1950, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(housing_value_1950) %>%
  filter(STATE == "New York" & B09001 > 0) %>%
  mutate(HousingValue1950 = B09001)%>%
  select(GISJOIN, HousingValue1950)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_housing_value_1950,
                         layer = census_tract_housing_value_1950_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% 
  merge(data1950, "GISJOIN") %>%
  filter(NHGISST == "360" & COUNTY == "081") 
  


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

write_rds(tracts1950, "shiny/housing_value/queens/1950/housing_value_1950.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1950)) %>%
  addLegend(pal = pal, values = ~HousingValue1950, opacity = 1.0)




```

```{r queens-housing-value-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960 <- read.csv(housing_value_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B7O001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:20])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:20])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianHousingValue1960=recode(MedianBracket,"B7O001"=2500,"B7O002"=6200, "B7O003"=8700,
                                         "B7O004"=11200, "B7O005"=13700, "B7O006"=16200,
                                         "B7O007"=18700, "B7O008"=22450, "B7O009"=29950,
                                         "B7O010"=35000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

queens_housing_value_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "81" & !is.na(MedianHousingValue1960)) %>%
  select(GISJOIN, MedianHousingValue1960)

queens_1960_map <- sf::st_read(dsn = census_tract_housing_value_1960,
                        layer = census_tract_housing_value_1960_layers)

queens_1960_map <- queens_1960_map %>%
  merge(queens_housing_value_1960, "GISJOIN")

queens_1960_map <- sf::st_transform(queens_1960_map,  
                                       crs="+init=epsg:4326")

queens_1960_map <- rmapshaper::ms_simplify(queens_1960_map)

# Set palette color

write_rds(queens_1960_map, "shiny/housing_value/queens/1960/housing_value_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(queens_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1960)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1960, opacity = 1.0)


```

```{r queens-housing-value-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(housing_value_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(CG7001)==FALSE & CG7001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:26])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:26])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianHousingValue1970=recode(MedianBracket,"CG7001"=2500,"CG7002"=6250, "CG7003"=8750,
                             "CG7004"=11250, "CG7005"=13750, "CG7006"=16250,
                             "CG7007"=18750, "CG7008"=22500, "CG7009"=30000,
                             "CG7010"=42500, "CG7011"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

tracts1970Print

queens_housing_value_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "81" & !is.na(MedianHousingValue1970)) %>%
  select(GISJOIN, MedianHousingValue1970)

queens_1970_map <- sf::st_read(dsn = census_tract_housing_value_1970,
                        layer = census_tract_housing_value_1970_layers)

queens_1970_map <- queens_1970_map %>%
  merge(queens_housing_value_1970, "GISJOIN")

queens_1970_map <- sf::st_transform(queens_1970_map,  
                                       crs="+init=epsg:4326")

queens_1970_map <- rmapshaper::ms_simplify(queens_1970_map)

# Set palette color

write_rds(queens_1970_map, "shiny/housing_value/queens/1970/housing_value_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(queens_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1970)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1970, opacity = 1.0)


```

```{r queens-housing-value-1980, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1980 <- read.csv(housing_value_1980) %>%
  filter(STATE == "New York" & C8J001 > 0) %>%
  mutate(HousingValue1980 = C8J001) %>%
  select(GISJOIN, HousingValue1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_housing_value_1980,
                         layer = census_tract_housing_value_1980_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="081") %>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/housing_value/queens/1980/housing_value_1980.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1980)) %>%
  addLegend(pal = pal, values = ~HousingValue1980, opacity = 1.0)

```

```{r queens-housing-value-1990, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(housing_value_1990) %>%
  filter(STATE == "New York" & EST001 > 0) %>%
  mutate(HousingValue1990 = EST001) %>%
  select(GISJOIN, HousingValue1990)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_housing_value_1990,
                         layer = census_tract_housing_value_1990_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="081") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/housing_value/queens/1990/housing_value_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1990)) %>%
  addLegend(pal = pal, values = ~HousingValue1990, opacity = 1.0)


```

```{r queens-housing-value-2000, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(housing_value_2000) %>%
  filter(STATE == "New York" & GB7001 > 0) %>%
  mutate(HousingValue2000 = GB7001) %>%
  select(GISJOIN, HousingValue2000)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_housing_value_2000,
                         layer = census_tract_housing_value_2000_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="081") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <- sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/housing_value/queens/2000/housing_value_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2000)) %>%
  addLegend(pal = pal, values = ~HousingValue2000, opacity = 1.0)


```

```{r queens-housing-value-2010, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(housing_value_2010) %>%
  filter(STATE == "New York" & JTIE001 > 0) %>%
  mutate(HousingValue2010 = JTIE001) %>%
  select(GISJOIN, HousingValue2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_housing_value_2010,
                         layer = census_tract_housing_value_2010_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="081") %>%
  merge(data2010, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <- sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/housing_value/queens/2010/housing_value_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2010)) %>%
  addLegend(pal = pal, values = ~HousingValue2010, opacity = 1.0)


```


STATEN ISLAND HOUSING VALUE

```{r staten-island-housing-value-1950, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1950 <- read.csv(housing_value_1950) %>%
  filter(STATE == "New York" & B09001 > 0) %>%
  mutate(HousingValue1950 = B09001) %>%
  select(GISJOIN, HousingValue1950)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1950 <- sf::st_read(dsn = census_tract_housing_value_1950,
                         layer = census_tract_housing_value_1950_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1950 <-
  tracts1950 %>% 
  merge(data1950, "GISJOIN") %>%
  filter(NHGISST == "360" & COUNTY == "085") 
  


# Set projection of tracts dataset to `projection` required by leaflet

tracts1950 <- sf::st_transform(tracts1950,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1950 <- rmapshaper::ms_simplify(tracts1950)

write_rds(tracts1950, "shiny/housing_value/staten_island/1950/housing_value_1950.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1950) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1950)) %>%
  addLegend(pal = pal, values = ~HousingValue1950, opacity = 1.0)




```

```{r staten-island-housing-value-1960, include=FALSE}

####1960 Census Tracts Median Family Income####

## Load data
## Create variable Median Bracket, filter out missing data

tracts1960 <- read.csv(housing_value_1960, 
                     stringsAsFactors = FALSE)%>%
                     mutate(MedianBracket=NA)%>%
                     filter(is.na(B7O001)==FALSE)

## Get column names

Brackets1960<-c(colnames(tracts1960)[11:20])

## Iterate through rows

for(i in 1:nrow(tracts1960)){
  
  ## Create DF with as many rows as families in data, labels are the name of the income bracket
  subDF<-tibble(FakePop=rep(Brackets1960, c(tracts1960[i,11:20])))
  
  ## Calculate median family income
  
  ## Find the middle row of the new dataset, ie the median family and 
  ## store what income bracket they fall into
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save in tracts1960
  tracts1960$MedianBracket[i]<-out
}

## Convert factors to middle of range

tracts1960Print <- tracts1960 %>%
                mutate(MedianHousingValue1960=recode(MedianBracket,"B7O001"=2500,"B7O002"=6200, "B7O003"=8700,
                                         "B7O004"=11200, "B7O005"=13700, "B7O006"=16200,
                                         "B7O007"=18700, "B7O008"=22450, "B7O009"=29950,
                                         "B7O010"=35000))
## SaveRDS file
#saveRDS(tracts1960Print, file="~/Downloads/nhgis0017_csv/1960MedianFamilyIncome_CensusTracts.RDS")

tracts1960Print

staten_island_housing_value_1960 <- tracts1960Print %>%
  filter(STATE == "New York" & COUNTYA == "85" & !is.na(MedianHousingValue1960)) %>%
  select(GISJOIN, MedianHousingValue1960)

staten_island_1960_map <- sf::st_read(dsn = census_tract_housing_value_1960,
                        layer = census_tract_housing_value_1960_layers)

staten_island_1960_map <- staten_island_1960_map %>%
  merge(staten_island_housing_value_1960, "GISJOIN")

staten_island_1960_map <- sf::st_transform(staten_island_1960_map,  
                                       crs="+init=epsg:4326")

staten_island_1960_map <- rmapshaper::ms_simplify(staten_island_1960_map)

# Set palette color

write_rds(staten_island_1960_map, "shiny/housing_value/staten_island/1960/housing_value_1960.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(staten_island_1960_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1960)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1960, opacity = 1.0)


```

```{r staten-island-housing-value-1970, include=FALSE}

#### Median Family Income 1970 Census Tracts####

tracts1970 <- read.csv(housing_value_1970, 
                       stringsAsFactors = FALSE) %>%
  mutate(MedianBracket=NA) %>%
  filter(is.na(CG7001)==FALSE & CG7001>0)

## Get column names
Brackets1970<-c(colnames(tracts1970)[16:26])
## Iterate through rows
for(i in 1:nrow(tracts1970)){
  
  ## Create DF with as many rows as families
  subDF<-tibble(FakePop=rep(Brackets1970, c(tracts1970[i,16:26])))
  
  ## Calculate median family income
  out<-unlist(subDF[round(nrow(subDF)/2),1])
  if(nrow(subDF)==0 | length(out)==0){next}
  
  ## Save 
  tracts1970$MedianBracket[i]<-out
}

## Convert factors to middle of range
tracts1970Print <- tracts1970 %>%
  mutate(MedianHousingValue1970=recode(MedianBracket,"CG7001"=2500,"CG7002"=6250, "CG7003"=8750,
                             "CG7004"=11250, "CG7005"=13750, "CG7006"=16250,
                             "CG7007"=18750, "CG7008"=22500, "CG7009"=30000,
                             "CG7010"=42500, "CG7011"=50000))
## SaveRDS file
#saveRDS(tracts1970Print, file="~/Downloads/nhgis0017_csv/1970MedianFamilyIncome_CensusTracts.RDS")

tracts1970Print

staten_island_housing_value_1970 <- tracts1970Print %>%
  filter(STATE == "New York" & COUNTYA == "85" & !is.na(MedianHousingValue1970)) %>%
  select(GISJOIN, MedianHousingValue1970)

staten_island_1970_map <- sf::st_read(dsn = census_tract_housing_value_1970,
                        layer = census_tract_housing_value_1970_layers)

staten_island_1970_map <- staten_island_1970_map %>%
  merge(staten_island_housing_value_1970, "GISJOIN")

staten_island_1970_map <- sf::st_transform(staten_island_1970_map,  
                                       crs="+init=epsg:4326")

staten_island_1970_map <- rmapshaper::ms_simplify(staten_island_1970_map)

# Set palette color

write_rds(staten_island_1970_map, "shiny/housing_value/staten_island/1970/housing_value_1970.rds")

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(staten_island_1970_map) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHousingValue1970)) %>%
  addLegend(pal = pal, values = ~MedianHousingValue1970, opacity = 1.0)


```

```{r staten-island-housing-value-1980, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1980 <- read.csv(housing_value_1980) %>%
  filter(STATE == "New York" & C8J001 > 0) %>%
  mutate(HousingValue1980 = C8J001) %>%
  select(GISJOIN, HousingValue1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <- sf::st_read(dsn = census_tract_housing_value_1980,
                         layer = census_tract_housing_value_1980_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1980 <-
  tracts1980 %>% filter(NHGISST == "360" & COUNTY=="085") %>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980 <- sf::st_transform(tracts1980,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1980 <- rmapshaper::ms_simplify(tracts1980)

write_rds(tracts1980, "shiny/housing_value/staten_island/1980/housing_value_1980.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1980)) %>%
  addLegend(pal = pal, values = ~HousingValue1980, opacity = 1.0)

```

```{r staten-island-housing-value-1990, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data1990 <- read.csv(housing_value_1990) %>%
  filter(STATE == "New York" & EST001 > 0) %>%
  mutate(HousingValue1990 = EST001) %>%
  select(GISJOIN, HousingValue1990)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1990 <- sf::st_read(dsn = census_tract_housing_value_1990,
                         layer = census_tract_housing_value_1990_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts1990 <-
  tracts1990 %>% filter(NHGISST == "360" & COUNTY=="085") %>%
  merge(data1990, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1990 <- sf::st_transform(tracts1990,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts1990 <- rmapshaper::ms_simplify(tracts1990)

write_rds(tracts1990, "shiny/housing_value/staten_island/1990/housing_value_1990.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1990) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue1990)) %>%
  addLegend(pal = pal, values = ~HousingValue1990, opacity = 1.0)


```

```{r queens-housing-value-2000, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2000 <- read.csv(housing_value_2000) %>%
  filter(STATE == "New York" & GB7001 > 0) %>%
  mutate(HousingValue2000 = GB7001) %>%
  select(GISJOIN, HousingValue2000)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2000 <- sf::st_read(dsn = census_tract_housing_value_2000,
                         layer = census_tract_housing_value_2000_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2000 <-
  tracts2000 %>% filter(NHGISST == "360" & COUNTY=="085") %>%
  merge(data2000, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2000 <- sf::st_transform(tracts2000,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2000 <- rmapshaper::ms_simplify(tracts2000)

write_rds(tracts2000, "shiny/housing_value/staten_island/2000/housing_value_2000.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2000) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2000)) %>%
  addLegend(pal = pal, values = ~HousingValue2000, opacity = 1.0)


```

```{r staten-island-housing-value-2010, include=FALSE}

# Coming soon

# Import Census Tract Data as data.frame Consult
# nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that column
# B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called for each new year
# of data you download from the codebook that comes with each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile
# data. Also drop census tracts which reported 0 median income

data2010 <- read.csv(housing_value_2010) %>%
  filter(STATE == "New York" & JTIE001 > 0) %>%
  mutate(HousingValue2010 = JTIE001) %>%
  select(GISJOIN, HousingValue2010)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts2010 <- sf::st_read(dsn = census_tract_housing_value_2010,
                         layer = census_tract_housing_value_2010_layers)

# *Select New York observations only using NHGISST variable NHGISST should be
# consistent between census years, but you might need to double-check this if
# you try 1960, 1970. *The NHGISST code is 360 for New York because New York's
# FIPS code is 360. Google New York FIPS code for more information about the
# FIPS system. *Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate' *Join the data1950 data
# with the MedianHHIncome variable by 'GISJOIN' so that the tract lines and
# income data are in one object *Subset to Manhattan county, which has FIPS code
# 061 *Can see other NY county fips codes at
# https://simple.wikipedia.org/wiki/List_of_counties_in_New_York

tracts2010 <-
  tracts2010 %>% filter(STATEFP10 == "36" & COUNTYFP10=="085") %>%
  merge(data2010, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts2010 <- sf::st_transform(tracts2010,  crs="+init=epsg:4326")

# Condense size of data for faster processing

tracts2010 <- rmapshaper::ms_simplify(tracts2010)

write_rds(tracts2010, "shiny/housing_value/staten_island/2010/housing_value_2010.rds")


# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts2010) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(HousingValue2010)) %>%
  addLegend(pal = pal, values = ~HousingValue2010, opacity = 1.0)


```



